### ISSUE TITLE
Allow \ in .conf files to allow multiple lines for run/task/service

### ISSUE THREAD

**Issue by hongkongkiwi** [troglobit/finit#186] opened 2021-08-18 04:20 UTC
I saw that there is an open task for a new .svc format #148 which breaks the service up into multiline syntax.

Before this new format is implemented, I was wondering if it's possible to just allow \ to breakup lines (like in shell scripts). This would mean we could have multiline service definitions with minimal work.... e.g.
```
service [2345] \
env:-/etc/conf.d/gpsd \
-N -s $GPSD_SERIAL_SPEED -S $GPSD_PORT \
 -F "$GPSD_SOCK" -D $GPSD_DEBUG_LEVEL \
$GPSD_OPTIONS "$GPSD_DEVICE" \
-- GPS Daemon
```

**Comment by troglobit** [comment] 2021-08-19 13:35
No, I'd much rather we implement the new format instead.  There's just too much that can go wrong with this proposal, because I've actually tried once before.

**Comment by troglobit** [comment] 2022-11-19 07:39
Since yesterday I've looked into this again, in part due to your comment in #148, but also  because I've been hit by the problem of long lines myself the last six months ... I admit I was wrong for closing this, sorry.

Looking into the matter a bit further, I realized one of the libraries we use carry `fparseln()`, from NetBSD, which sort of exist for this very use-case.

 - https://man.netbsd.org/fparseln.3

Only downside is that it's a bit too competent, not only does it prune .conf lines starting with comment, it also drops comments trailing a line ... unless it's escaped.  Nevertheless, I think `fparseln()` is the way forward here -- even though some uses may experience some regressions.  

Our own `test/initctl-status-subset.sh` immediately caught the problem. It has the following services:

    task manual:yes name:foo :1 serv -- Foo #1
    task manual:yes name:foo :2 serv -- Foo #2
    task manual:yes name:foo :3 serv -- Foo #3

The test fails since it cannot find any service with decription `"Foo #1"`.  However, escaping them works, so that needs to go into the documentation and ChangeLog for this upcoming release:


    task manual:yes name:foo :1 serv -- Foo \#1
    task manual:yes name:foo :2 serv -- Foo \#2
    task manual:yes name:foo :3 serv -- Foo \#3

**Closed** 2022-11-19 09:12 UTC
Labels: enhancement

**Comment by troglobit** [comment] 2022-11-19 09:14
There, fixed.

**Comment by hongkongkiwi** [comment] 2022-11-20 07:24
This is really helpful! Thank you.

Hmm yes, apart from comments and \ what other characters need escaping here?

**Comment by troglobit** [comment] 2022-11-20 10:42
None, only \ has special meaning.  The thing with # is that trailing comments was not supported before, but with the new implementation it is.  So you need to escape \\ and \# only.
